rvm:
  - 2.20
script: bash ./_deploy.sh
before_install:
  - bundle install
  # - sudo apt-get install imagemagick
  # - sudo apt-get install graphicsmagick
  # - gem install jekyll
  # - npm install gulp-cli -g
  # - npm install
  # - gulp
env:
  global:
    - GH_REF: github.com/FrontSeat/CSOneYearChallange
    - secure: euQUOjoPmxASiIgp4BcLdfJdgvy/yZIZtKq8qurYgrXgfDjngYOk0robA2ufkXhkV9o9lpaV2F08s87Mpx75+JtUr/xoDx0egpvB8f2PxxMKVvEOn6m5AsM4wEVcEQ3N0+LfFkhsDnDAemo8BrsC2PYO90hrwcHLsx7bCvF5N9WHcIxNK/9h/Vc+50R5Swhz730BD7DYKJXV8L4SI+qSFLlNdLP36BwW4oQPycgcEJ8hUGp23etAiNs01NRoas+Y4abPRkYaVA79MN+W3Tg+vv2at+0JfmdOVQVx6wThJW1iepzOnYJc73ZLg9x5eDqym5NqMgUjhAJZvTJpTjcpUZvLEBIgm+JaIJJh+PMQfS6zUQYXVzZLfcyzmZtU4htmDEtAdgTgpcVrIu927XuR6DDgtRTR9RefbMIbjPXDZj53aBylNlLYSpHm45Gx6dSnLUR8bg/m1u5PgSjumkdGymQrg7Nkx/YN5hzDRlo2kDHa/hA2umWgLV5Tc6uxMUPEOMjxp+eihVUvvoSSRerguuFL7R+34+ADzlxqaCSEgKZMelVK8kABPPCKWzOcI2cX+xUUPs/G34S6q8j637OQHqg/WHWhOEcc1flhV/iygzNWjWuinnXlkC1lgTJg/XZTn3Q6OLiVcjcVnSUu4JzQ3FNRIyIWjC0+nupyieQKEUc=
    - secure: fIt6V4UYG7x4k/bNbhZR2Ecb0Hgq1ImGqRK+a74MA1nAetuY33h27ju6Xjyb4L8CEKCvq5XGkhRecdZeCEdCxRNsLcOO5S3mzLkRLKjYj4y+j5Mk8eX7XBvxTgWh3tDjkeZw2cD9ET3QDG+0Uucyo5iX6+Tzg7wPFoRcaS/keFzpsFuM5wkdS39LYYVdGzdoGEnLJwrvwKej1gvBEEBma6vpz6txBm/pJcDVXqa6VM/dSSDCZsliZnOAje4QpscGAOq+CvXz3ERuOLbR2HCKTtjl3ykkg4cJCZle7YRfD/nJwZa4tirVY77GnhHnH/2z2/Rq9J+rJucQJlVBfzsNOcU/GJNoQN6kSr7RRwB4YsTUbWCPhzB+Gk2/BUjbJvqkOUqbT3jJk4aAAM6wQf/Oh0aD/oRdaRNhz9ISe2K11oSgySdAzfeZEIJSvBR/bHdYvP/cUkVmTmyEsTcuzrEOX22wYMk80NJLdqV/nKPL0vfWn/Zaz/OoQHJjYZ4QeawB4xo+0SJi5BvzpRhhq9UT6zysi38cJH0i/SaatAY5fpZbz9hCcS48xXPxhnvYYOEf4QRIJSqc+MJaFZ4+/SqvXK9x8+59Gcn77kQ3gEg4jxSuaqf9rFBaq61HD6Ug/4Z+2KD7N1Ql8LtQtJAVWCCeEWEodqctIrLNTDL2rNz1Gzk=
notifications:
  email:
    - lixinyang1026@gmail.com
