# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrontSeat
email: lixinyang1026@gmail.com
description:
  en: Computer Science one year challenge!
  zh: 计算机科学一年挑战！
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://challenge.frontseat.io"
index:
  en: en.html
  zh:
github_link:
  en: View on GitHub
  zh: 本文 GitHub 地址
github_username_0: li-xinyang
github_username_1: awpsawps12
feed:
  en: /feed-en.xml
  zh: /feed.xml
# Build settings
markdown: kramdown
