# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrontSeat
email: lixinyang1026@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://challenge.frontseat.io" # the base hostname & protocol for your site
github_username_0: li-xinyang
github_username_1: awpsawps12
# Build settings
markdown: kramdown
gems:
